"use client";

import React, { useEffect, useState } from "react";
import { useAuth } from "@/components/providers/AuthProvider";

interface Toast {
  id: number;
  message: string;
  type: "success" | "error" | "info";
}

export default function AdminSettingsPage() {
  const { session } = useAuth();

  const [orgname, setOrgname] = useState("");
  const [enableotp, setEnableotp] = useState(false);
  const [isactive, setIsactive] = useState(true);
  const [savingCompany, setSavingCompany] = useState(false);

  const [toasts, setToasts] = useState<Toast[]>([]);

  const addToast = (message: string, type: "success" | "error" | "info") => {
    const id = Date.now();
    setToasts((prev) => [...prev, { id, message, type }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 5000);
  };

  useEffect(() => {
    const fetchCompanyData = async () => {
      if (!session) return;
      try {
        const res = await fetch(`/api/company?orgcode=${session.orgcode}`);
        const data = await res.json();
        if (res.ok && data.success) {
          if (data.company) {
            setOrgname(data.company.orgname || "");
            setEnableotp(data.company.enableotp || false);
            setIsactive(data.company.isactive !== false);
          }
        }
      } catch (e) {
        console.error("Failed to load company data");
      }
    };
    fetchCompanyData();
  }, [session]);

  const handleUpdateCompany = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!session) return;
    setSavingCompany(true);
    try {
      const response = await fetch("/api/company", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          orgcode: session.orgcode,
          orgname: orgname,
          enableotp: enableotp,
          isactive: isactive,
        }),
      });
      const data = await response.json();
      if (response.ok && data.success) {
        addToast("Company settings updated successfully", "success");
      } else {
        addToast(data.message || "Failed to update settings", "error");
      }
    } catch (e) {
      addToast("Failed to connect to server", "error");
    } finally {
      setSavingCompany(false);
    }
  };

  return (
    <div className="flex flex-col gap-6 animate-fade-in relative">
      <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">Company Profiles</h2>
      <p className="text-slate-500 text-sm mt-1 mb-4">Configure organization metadata and validation rules.</p>

      <div className="bg-white/80 dark:bg-slate-800/70 border border-slate-200 dark:border-slate-700 rounded-2xl p-6 shadow-sm backdrop-blur-xl max-w-[600px]">
        <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-3 mb-5">Organization Profile Settings</h3>
        <form onSubmit={handleUpdateCompany} className="flex flex-col gap-5">
          <div className="flex flex-col gap-1.5">
            <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">Organization Name</label>
            <input 
              type="text" 
              className="w-full px-4 py-2 border border-slate-300 dark:border-slate-600 rounded-xl bg-white dark:bg-slate-900/50 text-slate-900 dark:text-slate-100 outline-none focus:ring-2 focus:ring-blue-500 transition-all" 
              value={orgname} 
              onChange={(e) => setOrgname(e.target.value)} 
            />
          </div>

          <div className="flex justify-between items-center bg-slate-50 dark:bg-slate-900/50 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
            <div>
              <div className="font-semibold text-slate-900 dark:text-slate-100">Enable Login OTP Code Verification</div>
              <div className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                If enabled, standard operator accounts require entering a 4-digit code generated by the administrator.
              </div>
            </div>
            <label className="relative inline-flex items-center cursor-pointer">
              <input 
                type="checkbox" 
                className="sr-only peer"
                checked={enableotp} 
                onChange={(e) => setEnableotp(e.target.checked)} 
              />
              <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
            </label>
          </div>

          <button 
            type="submit" 
            className="w-full mt-2 py-3 px-4 rounded-xl text-white font-medium bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 disabled:opacity-50 transition-all shadow-[0_4px_10px_rgba(37,99,235,0.2)]" 
            disabled={savingCompany}
          >
            {savingCompany ? "Saving Settings..." : "Commit Settings"}
          </button>
        </form>
      </div>

      {/* Toasts */}
      <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
        {toasts.map((toast) => (
          <div key={toast.id} className={`px-4 py-3 rounded shadow-lg text-white text-sm font-medium animate-slide-up ${toast.type === 'error' ? 'bg-red-500' : toast.type === 'success' ? 'bg-green-500' : 'bg-blue-500'}`}>
            {toast.message}
          </div>
        ))}
      </div>
    </div>
  );
}
