"use client";

import React, { useEffect, useState } from "react";
import { useAuth } from "@/components/providers/AuthProvider";

export default function UserOverview() {
  const { session } = useAuth();
  
  const [dashboardSummary, setDashboardSummary] = useState<{
    totalSlips: number;
    pendingAccounts: number;
    outstandingLedger: number;
    serverStatus: string;
    dbStatus: string;
  }>({
    totalSlips: 42, 
    pendingAccounts: 8,
    outstandingLedger: 12500,
    serverStatus: "AP-South-1 (Mumbai Pooler)",
    dbStatus: "Online",
  });
  
  useEffect(() => {
    if (session) {
      // Logic for fetching stats could go here
    }
  }, [session]);

  return (
    <div className="flex flex-col gap-6 animate-fade-in">
      <h2 className="text-3xl font-bold text-slate-900 dark:text-slate-100">Operator Dashboard</h2>
      <p className="text-slate-500 text-sm mt-1 mb-4">Welcome back. Here is a summary of your recent activities.</p>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        <div className="bg-white/70 dark:bg-slate-800/70 backdrop-blur-md rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-5">
          <div className="flex justify-between items-center text-sm font-semibold text-slate-500 dark:text-slate-400 mb-2">
            <span>Your Daily Slips</span>
            <span className="text-lg">📄</span>
          </div>
          <div className="text-3xl font-bold text-slate-900 dark:text-slate-100">{dashboardSummary.totalSlips}</div>
          <div className="text-xs text-slate-400 mt-2">Bills generated by you today</div>
        </div>

        <div className="bg-white/70 dark:bg-slate-800/70 backdrop-blur-md rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-5">
          <div className="flex justify-between items-center text-sm font-semibold text-slate-500 dark:text-slate-400 mb-2">
            <span>Pending Accounts</span>
            <span className="text-lg">🧾</span>
          </div>
          <div className="text-3xl font-bold text-slate-900 dark:text-slate-100">{dashboardSummary.pendingAccounts}</div>
          <div className="text-xs text-slate-400 mt-2">Accounts needing attention</div>
        </div>

        <div className="bg-white/70 dark:bg-slate-800/70 backdrop-blur-md rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-5">
          <div className="flex justify-between items-center text-sm font-semibold text-slate-500 dark:text-slate-400 mb-2">
            <span>System Status</span>
            <span className="text-lg">🟢</span>
          </div>
          <div className="text-3xl font-bold text-emerald-600 dark:text-emerald-400">{dashboardSummary.dbStatus}</div>
          <div className="text-xs text-slate-400 mt-2">Database connection healthy</div>
        </div>
      </div>
    </div>
  );
}
